version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/workspace/backend/src
      - ./backend/.env:/workspace/backend/.env  # ← 追加

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/workspace/frontend
      - /workspace/frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
